# Generated by Django 5.0.7 on 2025-09-12 14:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idempotencyrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='merchantcredit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='creditpool',
            constraint=models.CheckConstraint(check=models.Q(('available_amount__gte', Decimal('0.00'))), name='pool_available_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='merchantcredit',
            constraint=models.CheckConstraint(check=models.Q(('utilized_amount__gte', Decimal('0.00'))), name='mc_utilized_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='merchantcredit',
            constraint=models.CheckConstraint(check=models.Q(('credit_limit__gte', models.F('utilized_amount'))), name='mc_utilized_le_limit'),
        ),
    ]
